name: CI

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  Frontend:
    runs-on: ubuntu-latest
    env:
      UI_DIRECTORY: ./frontend

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '${{ env.UI_DIRECTORY }}/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-modules-

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.UI_DIRECTORY }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.UI_DIRECTORY }}

      - uses: actions/upload-artifact@v2
        with:
          name: "ui"
          path: "${{ env.UI_DIRECTORY }}/frontend/build"
