name: CI

on:
  push:
    branches: [development]
    paths:
      - frontend/**
      - .github/workflows/ci.yml
  pull_request:
    branches: [development]


jobs:
  Frontend:
    runs-on: ubuntu-latest
    env:
      ROOT_DIRECTORY: .
      UI_DIRECTORY: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '${{ env.UI_DIRECTORY }}/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-modules-

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "15.x"

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.UI_DIRECTORY }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.UI_DIRECTORY }}

      - uses: actions/upload-artifact@v2
        with:
          name: "ui"
          path: "${{ env.UI_DIRECTORY }}/build"

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r '${{ env.ROOT_DIRECTORY }}/requirements.txt'

      - name: Test Bazarr execution
        run: |
          bash '.github/scripts/build_test.sh'
